### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [keisentraut/age-keygen-deterministic#2]
Dear @keisentraut, Windows 7 x64 user here. Could you be so kind to generate `.exe` for the rest of us who are ordinary users without compilers?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by keisentraut** [comment]
Sorry for the late reply, this is just some hobby project. Here is your executable: https://github.com/keisentraut/age-keygen-deterministic/releases/tag/v0.4
Not sure if it will work, I don't have Windows.

**Comment by sergeevabc** [comment]
``` console
$ age-keygen-deterministic.exe
thread 'main' panicked at src/main.rs:65:71:
called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Uncategorized, message: "The handle is invalid." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ age-keygen-deterministic.exe --help
age-keygen-deterministic 0.3
Klaus Eisentraut
Tool for deterministic age key generation from passphrase.

USAGE:
    age-keygen-deterministic.exe [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --count <count>      optional number of secret keys which should be created [default: 1]
    -o, --offset <offset>    optional u64 offset for index of keys [default: 0]
```

@keisentraut, as you can see, the program works in a peculiar way, but I don't understand how to generate the key.

**Comment by keisentraut** [comment]
If you run it in ```cmd.exe``` then this program  should ask you interactively for a password. However, it seems you did this and it panic-ed in the function call to [rpassword::prompt_for_password](https://docs.rs/rpassword/latest/rpassword/fn.prompt_password.html). I don't know why and to be honest, I don't care and as I said I cannot test it, too. Try downloading rust/cargo for Windows for yourself, cross-compilation from Linux for Windows might be the issue but it could also be that the ```rpassword``` crate has some bug.
You are on your own, but feel free to submit a patch once you figure it out.

**Comment by sergeevabc** [comment]
Sorry, I'm an ordinary user, not a developer. I'm afraid if I start compiling the code, something will go wrong. Surely you have more experience in that field than I do. But it seems like you never intended to create a solution for a wider audience that is increasingly in need of digital security. Thank you for the clarification, Klaus.
